/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as AlbumIndexRouteImport } from './routes/album.index'
import { Route as AlbumCountryRouteImport } from './routes/album.$country'
import { Route as BuildTradeIdRouteImport } from './routes/build-trade.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIndexRoute = AlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumCountryRoute = AlbumCountryRouteImport.update({
  id: '/album/$country',
  path: '/album/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildTradeIdRoute = BuildTradeIdRouteImport.update({
  id: '/build-trade/$id',
  path: '/build-trade/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/album/$country': typeof AlbumCountryRoute
  '/build-trade/$id': typeof BuildTradeIdRoute
  '/album/': typeof AlbumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/album/$country': typeof AlbumCountryRoute
  '/build-trade/$id': typeof BuildTradeIdRoute
  '/album': typeof AlbumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/album/$country': typeof AlbumCountryRoute
  '/build-trade/$id': typeof BuildTradeIdRoute
  '/album/': typeof AlbumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/matches'
    | '/album/$country'
    | '/build-trade/$id'
    | '/album/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/matches'
    | '/album/$country'
    | '/build-trade/$id'
    | '/album'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/matches'
    | '/album/$country'
    | '/build-trade/$id'
    | '/album/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MatchesRoute: typeof MatchesRoute
  AlbumCountryRoute: typeof AlbumCountryRoute
  BuildTradeIdRoute: typeof BuildTradeIdRoute
  AlbumIndexRoute: typeof AlbumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/': {
      id: '/album/'
      path: '/album'
      fullPath: '/album/'
      preLoaderRoute: typeof AlbumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$country': {
      id: '/album/$country'
      path: '/album/$country'
      fullPath: '/album/$country'
      preLoaderRoute: typeof AlbumCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-trade/$id': {
      id: '/build-trade/$id'
      path: '/build-trade/$id'
      fullPath: '/build-trade/$id'
      preLoaderRoute: typeof BuildTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MatchesRoute: MatchesRoute,
  AlbumCountryRoute: AlbumCountryRoute,
  BuildTradeIdRoute: BuildTradeIdRoute,
  AlbumIndexRoute: AlbumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
